name: Safety Backend Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Safety Server
        uses: appleboy/ssh-action@v0.1.10

        with:
          host: 72.61.236.154
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          script: |
            cd ~/safety/safetytrainingacademy/trainingAcademy-backend

            echo "📥 Updating project..."
            git fetch origin
            git reset --hard origin/main

            echo "⚙️ Loading NVM..."
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            nvm use 20

            echo "📦 Installing packages..."
            npm install

            echo "🚀 Restarting PM2..."

            pm2 describe safetytraining > /dev/null

            if [ $? -eq 0 ]; then
              pm2 restart safetytraining
            else
              pm2 start server.js --name safetytraining
            fi

            echo "💾 Saving PM2..."
            pm2 save

            echo "✅ Deployment Finished"
